### ISSUE TITLE
No font 

### ISSUE THREAD

**Issue by Daveytron** [mjrgh/PinballY#10]
No font or text in menu after pressing 0. Windows 7 . Working on windows 10 
![20180920_093029](https://user-images.githubusercontent.com/43398603/45927809-581dd480-bf7c-11e8-91af-3750a12c9c2c.jpg)

**Comment by mjrgh** [comment]
Questions:

1.  Does this happen with any of the other menus (e.g., the main menu when you press "1", or the Exit menu when you press Escape)?

2.  Which version are you on?  Have you tried this with the latest (alpha 21 or alpha 22)?

3.  Are you seeing any error messages at any point?  Even seemingly unrelated?

**Comment by sebinouse** [comment]
PBY displays a right bracket **}** instead of a black plain arrow ► in the menu

Do we need a special font ?

**Comment by mjrgh** [comment]
I'm closing this since it looks like nmarlier84 foudn teh solution to the original issue:  Aero must be enabled if you're using Windows 7.  (This isn't an issue Windows 8+ because it's impossible to disable the equivalent of Aero on Win 8+.)

Also, there's the separate issue that sebinouse raised, related to the missing arrow character if you didn't have Wingdings 3 installed.  That's fixed in the Beta 2 release - you should no longer need any special fonts installed, just the basic set that comes with Windows.  (It's probable still possible to trigger similar problems if you manually delete some of the standard Windows fonts, but hopefully no one does that.)  Starting with the Beta 2, the program still tries to use Wingdings 3 if present, as it has some nicer arrow character than the other fonts, but the program falls back on similar characters in one of the standard fonts if Wingdings 3 isn't available.

**Comment by mjrgh** [comment]
Some more detail on this for anyone still running into this.  Atarian at vpforums figured out the specific system video setting that causes this:

https://www.vpforums.org/index.php?showtopic=40679&p=440525

There are two settings needed to fix it:

* Select an Aero theme (in the Windows control panels under **Appearance and Personalization**)

* Still in the control panels, under **Performance Information and Tools**, if you're using the **Adjust for best performance** option, switch to **Custom**, and make sure that the checkbox **Smooth Edges for Screen Fonts** is checked
