### ISSUE TITLE
DMD hidden behind backglass

### ISSUE THREAD

**Issue by cherlihy71** [mjrgh/PinballY#101]
I am using backglass images in PinballY along with enabled DMD for dmd videos.  No matter what I do, each time I start PinballY the DMD always starts behind the backglass image.  Any suggestions or did I miss something stupid?

Thanks

**Comment by mjrgh** [comment]
Are we talking about PinballY's own simulated-DMD window?  (The reason I ask is that there are at least two other DMD windows that people often have going as well: there's the "virtual DMD" window that comes from Freezy's dmd-extensions system, if you're using that, and there's the VPinMAME DMD window that pops up while you're playing.)

And I assume it's not possible to just resize the windows so that there's no overlap?  I always think in terms of a three-monitor cab setup, where the window ordering for backglass vs DMD just isn't a factor since they're on separate screens.  But I guess if you have them both on the same screen, you might want to arrange them so they overlap.

**Comment by cherlihy71** [comment]
I have Real DMD completely disabled.  I am using DMD videos in the virtual DMD on top of the backglass on a secondary monitor.  I tried scaling, exiting saving changes with no luck.  The DMD window still starts behind the full screen or scaled backglass.  I have to right-click each time I start pinbally or after playing a table, and selecting 'Show DMD' to get it to appear on top of the blackglass image.  Hope that makes sense.  I was looking for a 'window always on top' for the DMD window, but I don't think it exists.

**Comment by mjrgh** [comment]
Thanks for the details.  That kind of option ("keep DMD window in front of backglass window") sounds like exactly what's needed for your setup.  There isn't an option like that now, but I'll add one.

**Comment by cherlihy71** [comment]
Thanks again for the response and the consideration!  The front-end is top notch!

**Comment by mjrgh** [comment]
The new option is in the Beta 18 - it's on the Windows page of the options dialog.  Give it a try and see if it fixes it for you.

**Comment by cherlihy71** [comment]
I have tested the new option.  It works perfectly!  Thanks again!
