### ISSUE TITLE
Very long delay on table audio and volume ignored - beta 21.

### ISSUE THREAD

**Issue by sverrewl** [mjrgh/PinballY#121]
I decided to upgrade to beta 21. For all tables I have wheels, pf videos, backglass videos, real dmd videos and table audio. After upgrade the table audio isn't starting to play at startup. It comes between 34-37 seconds after I switch between the tables. And, it also seems to ignore the volume that I've set as low as 10%. 

Rolling back only the PinballY.exe to beta 20 and it works again.

Windows7 - 64bit and PinballY 21 beta 64bit from zip archive.

**Comment by mjrgh** [comment]
Hmm, seems to be working for me.  Any chance you have Table Audio muted in the system settings?  (Press '0' - digit zero - for the operator menu, check the Mute Table Audio setting)?  Your "delay times" sound suspiciously like the length of the audio track, and I'm guessing that the "delay" in the first play is actually not a delay at all, but the time it takes for the track to play through once on mute.  There seems to be a separate problem with the change to libvlc mp3 playback that the libvlc player isn't respecting the mute and volume settings on the 2nd and subsequent replays, so this would explain why a muted first play would turn into a full-volume second play.

**Comment by sverrewl** [comment]
Most of my audio files are from forum user GStav and they are approx 35 seconds long. I just did a test for what you are saying and - yes, mp3 was 35 seconds long and I clocked it manually to 35,7 seconds. Getting slow on my days ? ;)

 So it seems you are correct. However. I don't see what you are telling me. I've taken 2 screenshots from my setup, and provided what programs I have installed on my Win7. Might it be that I've got vlc 2.2.8 32bit which I believe (was/is ?) a requirement for Nailbuster's frontend maybe ?

https://www.dropbox.com/s/ksw537j3n01cedq/issue121.zip?dl=0

**Comment by mjrgh** [comment]
It's got nothing to do with any VLC **application** you have installed.  That's irrelevant - I know everyone thinks VLC versions are an issue because PinUp is so twitchy about VLC versions, but PinballY doesn't even *know* if you have any other VLC copies installed, and doesn't care.

If you don't have Table Audio muted, I'm not sure what's going on.  It sure **seems** consistent with a muted first play cycle given the timing, though.

**Comment by sverrewl** [comment]
Yeah. Well, for each table I scroll through, there is this delay. And if you don't know, I surely don't :)

**Comment by mjrgh** [comment]
Maybe try explicitly turning "Mute Table Audio" ON and then back OFF in the Operator Menu during the time it's "delayed", to see if that makes it come on?

**Comment by mjrgh** [comment]
The other thing you can try is creating some table audio files of distinctive different lengths, and see if the delay matches the track length - try creating a 15-second MP3 and see if the delay is 15 seconds, try a 120-second MP3 and see if the delay is 120 seconds, etc.  Use different enough lengths that it will be clear if that's what's going on.

**Comment by sverrewl** [comment]
Your assumptions are correct. A regular The Clash tune and I never heard it start since it went into Attract mode before any sound. Shorted it down to 15 sec in Audacity and, yes, started playing after me counting to 15.

**Comment by sverrewl** [comment]
Tried you Mute suggestion. Turning on both regular table and attract mode to mute and it starts playing the table audio like it ignores my choice ( 37 sec after table is scrolled too ), once it goes into attract mode, the audio is muted correctly. So, basically, it is only related to table audio.

**Comment by mjrgh** [comment]
Beta 22 has a fix for the looping volume reset problem.  I also tried applying the same fix to the first iteration, on the off chance that there's a deeper libvlc bug here causing your initial mute cycle.  Since I haven't been able to reproduce your initial-mute problem at all, it might be something else entirely, but I have a suspicion that it might have the same underlying cause as the looping problem, in which case it would be just the sort of thing that might act in random different ways on different machines.  Give it a try when you have a chance and see if it helps.
