### ISSUE TITLE
Question about wheel size and timer 

### ISSUE THREAD

**Issue by JeffD78** [mjrgh/PinballY#131]
Hi, I have find how to set the seamless loading, but i want to downsize the wheel image of the table and add extra time to the the launching overlay ( for don't seeing the table launch ) like add let the table appear 5sec after its done. I have find nothing about that in the help files. Thanks 👍

**Comment by mjrgh** [comment]
I'm not sure exactly what you're trying to do.  Are we talking about the background image (the image that covers the whole main screen), or the "icon"?  Could you be more specific about what "downsize" means?  Maybe you could mock up some graphics showing what you have in mind.

**Comment by JeffD78** [comment]
I want this icon smaller 
![FB_IMG_1587612429285](https://user-images.githubusercontent.com/63658977/80055920-381d1100-8523-11ea-92cc-ae9e88a61a69.jpg)

And wanna know if i can add extra time at this screen, so when the table appear, it was really loaded. Thanks

**Comment by mjrgh** [comment]
You can probably do what you want in terms of sizing with the custom drawing system - see Javascript scripting > Custom Drawing in the help.  

As for extra time with the screen displaying, probably not.  It's really up to Windows when a newly launched program comes to the foreground.  You can intervene with Windows API calls (see Javascript scripting > Calling Native DLLs from Javascript), but I don't have any suggestions for what specific interventions you might want to try there, other than saying that it's tough to get right because you'd be fighting with Windows (and Windows usually wins those battles).

**Comment by JeffD78** [comment]
Where can I check the original script of the loading layout ? To see what I need to change. Thanks 

Ok, that's not a good point for the timer ^^ I think I'm gonna buy a SSD

**Comment by mjrgh** [comment]
There is no script; that's just built in.  But you could implement your own version using the techniques described in the drawing layer section.  See also the "seamless loading" worked example for how to change the normal loading screens.

An SSD will at least speed up your loading times, but it probably won't do much to increase game startup speed.  Most games will open up a blank window and then chug along for several seconds loading assets before they display the actual game graphics.  That's the part that you can't do much about on the PinballY side - once the game opens its first window, that covers up the PinballY window, so it doesn't really matter what PinballY is displaying at that point.

**Comment by mjrgh** [comment]
I'm going to close this because I don't think there's anything actionable here on the PinballY side.
