### ISSUE TITLE
Turn off "admin VPX question"

### ISSUE THREAD

**Issue by fR33Styler-1971** [mjrgh/PinballY#138]
Dear mjr,

is there a way to turn of the "start vpx in admin mode" question?

I know, if i turn of start VPX via combat. mode "admin" it works... but i need VPX in admin mode to get a connection to PINsound which is also in admin mode (alternate ROM sound packs)...

Can i turn this off with some commandline, config parameters somewhere?

Best regards

**Comment by mjrgh** [comment]
First off, you might want to look into getting PINsound fixed so that it doesn't require admin mode.  Or maybe just try it without admin mode enabled, as it might not actually need it.  A requirement like that is usually a program bug, so you should report it to the PINsound people and see if they can fix it.

As for the "start bpx in admin mode" question, could be show me (screen shot) exactly what you're referring to?  And you've read the section on Admin Mode in the help, right?

**Comment by fR33Styler-1971** [comment]
Thank you very much for answering mjr!

The Problem here is, PINsound will not fix it (Admin Mode) because the new/up-to-date software has a completely different philosophy ("edit sounds only" instead of "synch between VPX & PINsound")

I have clearly read your help (in my opinion the best help page for this kind of documentation on the net -helped me sooo much, also for Pinscape etc. - that was praise :-)

And for PinballY i run PinballY Admin Mode.exe itself which launches PinballY.exe in regular user mode... and this works perfect for my tasks (cool solution).


If VPX.exe runs in regular user mode -> there´s no synch with "PINsound" possible.

And if i set the "Run as Administrator" checkbox in VPX.exe's file properties, i always get once this message (starting out of PinballY):
![MSG](https://user-images.githubusercontent.com/17712897/85012315-22af1680-b163-11ea-8780-a77a9b73bc96.png)

And this was my question: is it possible to turn this question off somehow?

Greetings

**Comment by mjrgh** [comment]
That message should actually only occurs if you're **not** running **PinballY Admin Mode.exe**, because what it's doing is asking permission to restart by exiting and launching **PinballY Admin Mode.exe**  Are you absolutely sure you're running **PinballY Admin Mode.exe**?

**Comment by fR33Styler-1971** [comment]
Iam Sorry... this was the wrong screenshot... this is the right one:
![Unbenannt3](https://user-images.githubusercontent.com/17712897/85161049-80288d80-b25f-11ea-9159-1ee5b608f2cf.png)

I started PinballY Admin Mode.exefor sure... i have a *.bat file incl.

`@echo off
c:
cd c:\DirectOutput
start /min DOFLinx.exe

c:
cd C:\PinUPSystem\PinUPPlayer
start /min PinUpPlayer.exe

c:
cd C:\PinAffinity64\
start /min PinAffinity.exe

c:
cd C:\PinballY\
start PinballY Admin Mode.exe

c:
cd C:\PinSoundStudio\PinSoundStudio-09\
start PinSoundStudio.exe /minimized`

**Comment by mjrgh** [comment]
Good, that's the message you should be seeing in this case.  And sorry, there's no "checkbox option" for turning that off.  It's there in lieu of the Windows UAC warning about launching an elevated-privilege process, so I don't want to add an option to disable it because of the potential impact on system security.  If you really want to bypass it, you could do it with Javascript; see the help section Javascript scripting > System Objects > Window Objects > mainWindow > Menus.  You'd just have to write a listener for the **menuopen** event and menu ID "approve elevation".

**Comment by fR33Styler-1971** [comment]
Thanks a lot for your help mjr, I really appreciate it!

I just understand HTML, CSS and a little PHP... no JS... but with trail on error i find my way (same [here](https://github.com/mjrgh/PinballY/issues/106)).

So i need a little help... 

I have interpreted that i should put some code into the "main.js"?
And from your documentation and my "little less understanding of JS" it should look like something like this:

`// Listen for "Visual Pinball X Admin privileges Message and confirm"
mainWindow.on("menuopen", (ev) => {
    if (ev.id = "approve elevation") {
        // tell the system to apply our updates
        ev.menuUpdated = true;
    }
});`

But this doesn´t work (also with some different adjustments like ev.id == "approve elevation" etc.

Can you point me in the right direction?
Is the "approve elevation" correct (due to the "space" inbetween etc.)?

A little help is very welcome.

Thank you!

**Comment by mjrgh** [comment]
You're on the right track.  You do need the "==" notation - one "=" is "assign" in Javascript, two "==" is "is equal".  What you need to do when you recognize the menu is (1) cancel the default system action for the event by calling **ev.preventDefault(),** so that the system doesn't display the menu, and (2) actually execute the command that approves the elevation.  But I see that the command to do that isn't actually exposed to js - I guess I decided to only allow manual activation by the user, because of the security implications.  I'll have to think about it.

**Comment by fR33Styler-1971** [comment]
thank you for the statement. Let me know, when you thought about it... and it´s possible in JS in your next versions (if you like to do this).

**Comment by fR33Styler-1971** [comment]
Any new thoughts Mike? :)

**Comment by mjrgh** [comment]
I added an option for this in 1.1.
