### ISSUE TITLE
unable to drag-drop media pack

### ISSUE THREAD

**Issue by toccata10** [mjrgh/PinballY#14]
It seems a very cool feature, but I can't make it work. I tried with this on my acdc table:
http://vpuniverse.com/forums/files/file/3118-acdc-stern-2013-media-pack/
Tried with various other media pack. No luck so far: I need to unack and drag the wheel or playfield.
![drag-pb-01](https://user-images.githubusercontent.com/7478580/47371083-6c720000-d6e7-11e8-8e1d-8b2fd1c8b0fd.PNG)

**Comment by mjrgh** [comment]
I tried that same file, and it's working fine for me.  When you download it, what's the file name you're seeing in the local file system?  For that particular file, it should be ending with .rar to indicate that it's a RAR archive.  The drop file mechanism senses the file type based on the name suffix, so if that's not being set right, that would explain why it's not being seen as an archive when you drop it.

**Comment by toccata10** [comment]
ACDC (Stern 2013)HPMP.rar is the name of the file. Draging an individual file works (playfield still image or video for example), but not the pack. I tried to install pinbally with the x64 msi files (I had it just uncompressed before). No difference. It's located in c:\Visual_Pinball\PinballY
Could something be missing on my system ?

**Comment by mjrgh** [comment]
What's the exact sequence of messages you see on the screen during the drag operation?

Also, perhaps you could try manually renaming the file to something really simple, say "Test.rar", just to make sure there aren't any mysterious hidden characters in the name or anything weird like that.

**Comment by toccata10** [comment]
A screen recording of my pb
[drag-drop-pb.zip](https://github.com/mjrgh/PinballY/files/2510039/drag-drop-pb.zip)

**Comment by mjrgh** [comment]
One more question.  I noticed in the video that none of the individual image filenames have extensions (.JPG, .PNG, etc) in your unpacked folder tree.  I'm assuming that's just because you have Windows Explorer set to "hide filename extensions", and that the files actually do have the extensions.  And the copy of the RAR that I downloaded from your link does have the extensions, so again, assuming we're really using the same file, it shouldn't be any different on your system.  But just to be sure, when you look at the RAR with a RAR tool, you do see the extensions, right?  (Because if they're missing, that's the whole problem.)

**Comment by maperks** [comment]
I tried with several different HyperPin media packs and it failed for me too. Same error message as toccata

**Comment by mjrgh** [comment]
Should be fixed now in the Beta 2 release.

**Comment by toccata10** [comment]
Thanks for the beta release with all these improvements. I updated using the minimal update, but the new 7z.dll is not included in the package, so it didn't work until I downloaded the 7z.dll from github.
I think it should be added to this package (7z.dll doesn't seem to be included in the x64 zip package either).

**Comment by mjrgh** [comment]
> I updated using the minimal update, but the new 7z.dll is not included in the package,

Right: per the description...

"The Minimal ZIP package is much smaller because it only has the core PinballY files, without any of the required third-party components."

7z.dll being a third-party component, it's not included.  (If I started including third-party components in the "minimal" update, it would be exactly the same as the "full" update, so there'd be no point in having a separate version.)

**Comment by mjrgh** [comment]
And by the way, you should probably grab the full install for this round, since the minimal installer doesn't have the new Javascript DLL either, being another third-party DLL.

**Comment by toccata10** [comment]
OK. Thanks. Unless I make a mistake, I can't see this 7z.dll in the full portable version neither (http://www.mjrnet.org/pinscape/downloads/PinballY/PinballY-64bit-20190122.zip)

**Comment by mjrgh** [comment]
> On a side note, with my computer, I had to rename the "ffmepg64" folder to "ffmepg"

I'm guessing you installed from the ZIP download rather than the MSI?  It looks like this is another bug in my script that builds the ZIP; the files should have been installed into .\ffmpeg in the first place.  I'll fix it for future updates.
