### ISSUE TITLE
IPDB Database - More Robust info

### ISSUE THREAD

**Issue by xantari** [mjrgh/PinballY#157]
Just wanted to let you know i've published a open source IPDB database file in .json for more robust information lookup if you want to use it instead of the .csv file.

https://github.com/xantari/Ipdb.Database

Data models in the Models project.

**Comment by mjrgh** [comment]
Thanks for letting me know.  Looks like a nice project.  I'm going to continue using the CSV in PinballY for now, since it's more convenient for my purposes, and since I had to do some manual modification of the IPDB data for optimal use in PinballY.  At some point I might look at setting up a mechanical cross-reference process to scan your JSON data for new items that can be imported into my database, to bring it up to date - that might be a bit easier than doing that via another scrape of the IPDB site (although ultimately it's probably about a wash, since it'll require manual review of the new rows in any case).

**Comment by mjrgh** [comment]
I'll also add a reference to your database in my notes about updating the IPDB import, as a possibly more convenient source for the data.

**Comment by xantari** [comment]
Sounds good. I don't think c++ has anything similar LINQ, but in C# it's one line of code to load the database in memory and you can query on any facet of the data using LINQ. I made sure all the data points you had in your .csv file were present in the .json except for AltName. 

Here is the code to rebuild your .csv file in C# in six lines of code (minus AltName):

```cs
var sb = new StringBuilder();
sb.AppendLine("Name,Manufacturer,ManufacturerShort,Year,Players,Type,Theme,IPDBID");
var csvRows = database.Data.Select(c => $"{c.Title},{c.Manufacturer},{c.ManufacturerShortName},{(c.DateOfManufacture.HasValue ? c.DateOfManufacture.Value.Year.ToString() : "")},{c.Players.ToString()},{c.TypeShortName},{c.Theme},{c.IpdbId}");
foreach (var row in csvRows)
    sb.AppendLine(row);
File.WriteAllText("C:\\ipdb.csv", sb.ToString());
```

**Comment by mjrgh** [comment]
Great, thanks. I noticed that you normalized the manufacturing date from IPDB into a real date value for the JSON, which is a nice bonus, since that was a bit of a pain with the raw IPDB data given all of the different year formats they use.  I didn't look to see if you also normalized the theme data - IPDB has some variability there where they use different delimiters ("," in some cases, " - " in others).

AltName probably isn't applicable to your version, since that's going to be mostly useful for programs like PinballY that work with virtual re-creations.  I use it to fuzzy-match .vpx/.fp filenames against IPDB titles to try to guess at which IPDB entry a given file might correspond to.  It's useful in that context because a few tables have official titles that are longer than what people usually call them, the original motivating example being "James Cameron's Avatar", which most people just call "Avatar".  The common name elides so much of the full title that fuzzy match algorithms tend to consider it a poor match to the full title.  But I don't know, maybe it's worth special-casing into your data set, if you think anyone else will want to do that kind of matching against external data where people are using common names for tables.

**Comment by xantari** [comment]
Didn't normalize the theme data but will look at it to see if that can be updated. Makes sense about the alt name scenarios like avatar.
