### ISSUE TITLE
PBY's Solid State table video DMD high score displays

### ISSUE THREAD

**Issue by 11islander22** [mjrgh/PinballY#161]
PBY video DMD high scores for a Solid State table beautifully keep synch to the table's PinMAME DMD color changes but not to table's video DMD brilliance changes also stored in the registry at **Computer\HKEY_CURRENT_USER\Software\Freeware\Visual PinMame\TABLE_ROM_NAME**

Could you please also incorporate the **dmd_perc0**, **dmd_perc33** and **dmd_perc66** registry values into PBY's Solid State table video DMD high score displays?

I changed from PinMAME's defaults of dmd_perc0 = 20 to dmd_perc0 = 0.  This change turns off non-image DMD pixels rather than illuminating them at PinMAME's default brilliance of 20 out of a 0-255 scale.  I found that real DMD displays do not illuminate non-image pixels.  My new setting makes Visual Pinball Solid State tables video DMD's more realistic and vivid.  I'd like PBY's video DMD high scores to be identical to VP's video DMD look.

**Comment by mjrgh** [comment]
Agree this would be worthwhile for the sake of customization.   

For what it's worth, though, the reason the defaults (in PinMAME and in PinballY) use a non-zero brightness for "off" isn't that the original plasma DMDs used non-zero brightness for "off".  Rather, it's because the original plasma DMD pixels were visible as dark orange dots when completely off, visibly a different color from the black carrier.  A non-zero brightness in the video version better simulates this effect and makes it look a little more like the real thing.

![unpowered-plasma-dmd](https://user-images.githubusercontent.com/8271213/108558119-51f7c380-72ae-11eb-91c9-3c76cadbb4bd.jpg)

But I can understand wanting to crank up the contrast anyway as a personal taste thing.

**Comment by 11islander22** [comment]
Thanks for the DMD info and your consideration of the enhancement.  Looking at RAB’s DMD, the unlit pixels are not nearly as noticeable as the unlit pixels in the DMD picture you sent.  RAB probably uses a colored filter in front of the DMD to somewhat hide the dots and increase the contrast?  Anyway, thanks again!

[cid:image003.jpg@01D7076F.7E779750]

**Comment by mjrgh** [comment]
Should be fixed in 1.1 Beta 1.
