### ISSUE TITLE
Typo bug in new GameWheel Option  (s) instead of (ms)

### ISSUE THREAD

**Issue by worksasdesigned** [mjrgh/PinballY#173]
Typo bug in new GameWheel Option .

In autorepeat Rate is set in "ms" but text shows (s) instead of (ms).

A set default value of 100-250 would be better. Its so super fast changing tables that it looks more like a video stream than changing tables. Adujsting to 0.25 doesnt work but 250 does.

Just a typo.

**Comment by mjrgh** [comment]
Sorry for the confusion - that "(s)" wasn't a time unit, it was meant to be read as a singular/plural, "Rate(s)", as in "Rate Or Rates, one or more".  But I can see why you'd read it as "seconds".  It's all explained in the help (click on the little "?" at the top of the dialog), but I'll remove the "(s") because I'm sure many people will read it the same way.

**Comment by mjrgh** [comment]
Fixed in 1.1 Beta 3.
