### ISSUE TITLE
Record-Process-window recorded by "capture images & videos"

### ISSUE THREAD

**Issue by AndyPinB** [mjrgh/PinballY#19]
Hi,

i have a problem to capture media. Once i start to capture an image and/or a video from the playfield the "Record Process window" will also be recorded 

![family guy stern 2007](https://user-images.githubusercontent.com/44598431/47867964-5826b500-de03-11e8-9a1b-0724a8a6823c.png)

[Playfield_Video_with_Process_Window.zip](https://github.com/mjrgh/PinballY/files/2539425/Playfield_Video_with_Process_Window.zip)

The Backscreen shows the process windows during the record of the playfield

![img_20181031_221620](https://user-images.githubusercontent.com/44598431/47868827-90c78e00-de05-11e8-9384-8383db66fd1b.jpg)

I don't have the problem the backscreen and the virtual dmd. 

Maybe someone has a suggestion how to solve. 

Thanks in advanced.

Best regards,

Andy

Setup:

PinballY 1.0.0 Beta 1 (64Bit)
Windows 10 (1803)
Nvidia GTX 1050 (Driver Build: 23.21.13.9135) > all 3 screens connected to this graphic card
AMD Ryzen 3 2200G

**Comment by sebinouse** [comment]
I just recorded more than 100 images (for TPA), and capture is working as expected.
The "Record Process window" is displayed on another other screen just before capture.

I tried on Playfield, Backglass and DMD : no issue for me.

Maybe you should have a closer look to your screen setup ...

For information here is my setup

PinballY 1.0.0 Beta 1 (64Bit)
Windows 10 (1803)
Nvidia GTX 1050 Ti > all 2 screens connected to this graphic card 

Playfield Screen 1, Backglass & DMD Screen 2 (same top, 2 at the right of 1)

**Comment by mjrgh** [comment]
AndyPinB - I'm not sure what's going on.  The status window is **supposed** to be moved automatically out of the way of whichever window is being captured at any given time.  So evidently there's some miscalculation of the bounds of the playfield window and/or the backglass window.

One thing I'm not clear on.  You said: "The Backscreen shows the process windows during the record of the playfield".  Does that mean you see **two copies** of the status window **during** the recording process?  Or does it mean that the status window moves to the backglass area (as it should) during the recording process, but later on when you review the captured video, the captured playfield video contains an image of the status window **that you didn't see during the capture process itself**?  

I know this is all splitting hairs and hard to describe properly, so the easiest thing might be if you could make a video of the full capture process so that I can see exactly what's going on during the capture and then see the results of the process.  Something like this:

1. Manually delete all of the previously captured videos for some game you can test with.  Make sure that everything old is gone and that you're seeing the ugly default graphics for the game in all three windows in PinballY.

2. Point a camera at your cab so that you get a view of all three screens simultaneously.  Start taking a video of this view.

3. With the video recording running, initiate the capture process for the game and let it run all the way through.

4. Upload the full-cab-view video of the capture + the newly captured playfield video.

The full-cab-view video doesn't have to be super high-res; I really just want to see exactly where the capture status window appears at each point through the process.

It might also help to know your exact video screen setup - size of each monitor, resolution settings, zoom settings, DPI settings, and location in the Windows virtual desktop (the little "1"-"2"-"3" diagram showing monitor locations in the Windows screen resolution control panel).

**Comment by mjrgh** [comment]
Closing due to lack of response - I'm going to assume this is no longer an issue or that you're no longer using the program.
