### ISSUE TITLE
multiple DMD not found messages

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#23]
I am running Beta 2 (I was waiting for the ZIP file fix). If I don't have my Pin2DMD connected I get an error message. But then when I run a table I get multiple "Pin2DMD not found" error messages from PinBallY.

These kind of messages should only be displayed once (or user prompted to say he got it and displayed once).

**Comment by maperks** [comment]
(Pin2DMD doesn't like a long USB cable).

**Comment by mjrgh** [comment]
If you select Auto mode for the DMD, you shouldn't get any error messages.

**Comment by maperks** [comment]
I have selected Auto mode. This problem occurs when the DMD is not connected or powered. PinballY is looking for it and cannot communicate with it - hence the error messages.

**Comment by mjrgh** [comment]
Could you take a screen shot of the error message(s) (each one if there are multiple ones) and upload them here?

**Comment by mjrgh** [comment]
Pinging to see if you're still there - I need the information above if you want me to investigate further.

**Comment by maperks** [comment]
Apologies on the delay. I couldn't reproduce the multiple error boxes but here is the message I get when Pin2DMD is not connected or powered.

![pinbally_dmd](https://user-images.githubusercontent.com/41599843/52677565-5d17fc00-2efc-11e9-9a91-2c408c95e69d.PNG)

**Comment by mjrgh** [comment]
Ah, okay, I see what's going on.  That error alert is actually coming from your Pin2DMD DLL.  I'm afraid there's nothing PinballY can do to suppress it other than not loading the DLL in the first place, because what's triggering the message is merely loading the DLL.  If you have the DMD set to "Auto", PinballY loads the DLL in order to detect if the device is present.

You could talk to the Pin2DMD guys about it and see if they can fix it on their end.  Another option might be to upgrade to dmd-extensions (https://github.com/freezy/dmd-extensions) - I think it's a little nicer about this.

**Comment by maperks** [comment]
I will have to try dmd-extensions when I get time. Let's consider this issue closed now I know where the error message is coming from.
