### ISSUE TITLE
Could not find a way to re-edit a table

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#24]
If I partially edit a table and then I want to go back and change something, the edit item is missing from the  table menu. How do I get back to this without resetting the database?

**Comment by mjrgh** [comment]
Try "0" for the Operator Menu, which has a Game Setup option always available.

**Comment by maperks** [comment]
I do not see a game setup option on the operator menu.

I do not understand why the GameSetup is removed after entering data the first time. What happens if you made a typo or want to make any change. Why not simply always leave it on the menu and include an option in the operator menu to "hide or show" the GameSetup menu. That allows someone to partially lock the configuration so kids or whoever cannot accidentally change something.

**Comment by maperks** [comment]
Please reopen this issue.

**Comment by mjrgh** [comment]
> I do not see a game setup option on the operator menu.

It should be the first item, right at the top:

![pbyoperatormenu](https://user-images.githubusercontent.com/8271213/51765637-2c773c00-208d-11e9-8660-0466982c4a3e.png)

You're pressing the "0" (digit zero) key, right?  (Unless you remapped it - check under the Button settings for the key assigned to Service 4/Enter.)  If your operator menu doesn't look like that, could you upload a screen shot?

> I do not understand why the GameSetup is removed after entering data the first time. 

Because Game Setup is fundamentally an operator function.  One reason to isolate operator functions onto a separate menu is just to keep the main menu from bloating (even more than it already is, anyway).  Another is that a lot of people don't want setup functions exposed to "civilians" who might be using their machines, so that random users don't accidentally screw something up.  

Remember that you can customize any of the menus now through Javascript, so if you really want Game Setup to appear on the main menu permanently, you can do that with a little script code.

**Comment by maperks** [comment]
I was using the letter "O" which gives me a completely different menu. O is for options. Perhaps you need a slashed zero to be clearer (https://en.wikipedia.org/wiki/Slashed_zero).

**Comment by mjrgh** [comment]
> Perhaps you need a slashed zero to be clearer

0/O is certainly notoriously ambiguous.  I usually try to remember to write "'0' (digit zero)" or "'O' (letter O)", but I guess I didn't think to do that this time.  

(Assigning this to the digit-0 key for this wasn't entirely my idea, by the way.  I used this default because digit 0 is the hard-coded VPinMAME mapping for the Service Enter/Select button, which is the key that enters Operator Menu mode in most of the later ROM-based games.  It seems like the obvious analog at that level.  Using letter-O for Options was probably a confusing choice given the digit-0 assignment, but at least that one's somewhat mnemonic.)
