### ISSUE TITLE
Drag and drop does not work in administrator mode

### ISSUE THREAD

**Issue by dch850** [mjrgh/PinballY#28]
When I launch PinballY in administrator mode (to avoyd an alert message when I lauch a VPX table), it's impossible to drag and drop files, I have to restart pinballY in non-administrator mode and then it works.

**Comment by mjrgh** [comment]
Please read the Help system section "Administrator Mode".  You should **not** be launching PinballY in Admin mode.  You also shouldn't be running VP in Admin mode.  Windows by design imposes numerous restrictions on inter-process communications between Admin mode and User mode processes, which is why things like keyboard monitoring and drag-and-drop won't work when mixing the modes.  Admin mode is intended (by Microsoft) to be reserved for privileged system tools doing system configuration tasks; using it for regular application programs is a misuse, partly because it weakens system security but mostly because it makes your life a nightmare trying to work out all of the weird incompatibilities like one you're running into here.
