### ISSUE TITLE
Direct table launch with pbfx3 does not work

### ISSUE THREAD

**Issue by dch850** [mjrgh/PinballY#30]
With parameter -table_[TABLEFILE] with the pinballfx3.exe, you should be able to launch table directly without going through the pbfx3 menu page. It does not work and you come ine the pinballfx3 menu whatever the table you launch.

I did some test in the pinballfx3 configuration  with the citadel table : 
I tested to put -table_citadel.pxp instead of the -table_[TABLEFILE] parameter => not working
I tested to put -table_citadel => it's working
I tried to put -table_citadel.pxp while leaving the "file extention" datafield empty instead of *.pxp => it's working

While putting -table_[TABLEFILE] and leaving the "file extension" data field empty, I'm able to launch the table I want from pinballY (but the system is not able to find new tables).

**Comment by mjrgh** [comment]
FX3 direct launching is working for other people, using the default settings - those default settings weren't my invention, but came from someone who had it set up and working.  You might want to change back to the default settings (to undo the new problems you created with your changes, like being unable to discover new table files), and then ask on vpforums if someone can help you get the settings right.  I'm afraid I can't help directly because I don't use FX3, but there are several people on vpforums who do, so I'm sure someone there can help you out.
