### ISSUE TITLE
Audio in videos on Real DMDs does not play until looped/on first pass

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#38]
Ok, so this might be a "weirdo" thing/edge case, but still likely not intended behavior:

For my "Favorite" tables, I play video clips "on the dots", as people play on toppers, etc. 
The audio does not play on the first pass, but after 1. a loop or 2. post PinballY Scores screen.

Probably didn't imagine someone not playing silent DMD recordings on that display.

On the PinballY software DMD, the behavior is as expected; audio plays.

**Comment by mjrgh** [comment]
Well, this is one of those amusing cases where it's the opposite of what it appears.  The **actual** bug is that audio plays at all.  It's not supposed to; the real DMD video is supposed to play back muted.  The bug is that the mute setting isn't sticking past the first iteration.  The assumption is that you wouldn't want audio in the DMD video to interfere with your foreground audio.  But I suppose I could try un-muting it and see if anyone complains.

**Comment by mjrgh** [comment]
Audio is enabled now (beta 6).
