### ISSUE TITLE
Seamless/"Seamless" Table loading

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#39]
Picture/1K words:

https://youtu.be/xuGrz2hcB9s

I am a programmer, but not Windows - this seems doable however in the current implementation of PinballY, but is admittedly a "naivé" assumption on my part. Is this viable/interesting to you?

**Comment by Adeysan** [comment]
I'd also love to see something like this - but perhaps with the ability to show the loading/running messages on the DMD (maybe as PNGs, so we can customise them).

**Comment by Cley85** [comment]
Hi, when this was released? Can't wait to try this awesome feature. 
Default loading screen is boring me 😂

**Comment by mjrgh** [comment]
Beta 17 has some new Javascript features that make this possible.  See the help, under Javascript scripting > Worked Examples > "Seamless" Game Launch.  

It's not quite a checkbox option, but I think this is better because it gives you a lot more flexibility for customization than a checkbox option could.  The examples show how to implement the original idea in a few lines of Javascript code, as well as offering some ideas for further elaboration, such as Adeysan's idea to display the status messages in the DMD window.
