### ISSUE TITLE
Media not appearing

### ISSUE THREAD

**Issue by dexje** [mjrgh/PinballY#4]
I have imported media into PinballY, which gets saved in the corresponding directories (.\PinballY\Media\ in my case) successfully. But no media files are shown inside PinballY.
How can I fix that?

I have attached my settings.txt if that helps. The PinballY.log file is empty.
[Settings.txt](https://github.com/mjrgh/PinballY/files/2255176/Settings.txt)

**Comment by mjrgh** [comment]
Could you give me the exact series of steps you performed?  File names and locations would also be helpful, as might a DIR /S listing of your media folder and copies of the XML files from your PinballY\Databases folder.  

In general, the media file names should match the game titles, so if the "wheel" display is showing "Funhouse" as the title, the media files it's looking for will be "Funhouse.mp4" and "Funhouse.jpg" and so on.  So you can check to see if those are matching up as expected.

**Comment by dexje** [comment]
Thats not the case for me:
the table is named "Attack from Mars" in the wheel view. All the media files are named "Attack from Mars (Bally 1995)".
i have attached the requested files.
[Databases.xml and Media Folder Dir.zip](https://github.com/mjrgh/PinballY/files/2259490/Databases.xml.and.Media.Folder.Dir.zip)

Is the program supposed to rename the files?

Steps:
1. Edited the game info of the table via the game setup menu.
2. Downloaded the media pack from here: https://www.vpforums.org/index.php?showtopic=10436
3. Drag and dropped all the files into pinbally.
4. Received a successful import message.
No media shows up.

**Comment by mjrgh** [comment]
Sorry - right - the general pattern is "Title (Manufacturer Year)".  

When you install a media pack, the system actually will rename any files that don't conform.  It'll prompt you if this is necessary, to make sure that you didn't mean to install them for a different game, so if you didn't see any questions about that, they must have already been in the correct name format, which it looks like they are.

Looking through your files, I see two odd things:

1.  The "name" setting in your table database file is "Attack from Mars (Bally 1995) g5k 1.1".  Did you add intend to add that extra text after the manufacturer/year section?  That's actually going to cause some problems for the title recognition when PinballY reads the database file, so that might be the problem right there (or part of it).

2.  It looks like the database file for your system is named "Databases".  That is, your XML file is called "Databases.xml" and your media folder is "...\Media\Databases\..."  Was that intentional?  It should normally be simply the name of the system - "Visual Pinball", "Future Pinball", etc.  I think it's going to cause some confusion down the road if you ever install more than one system.

**Comment by dexje** [comment]
"When you install a media pack, the system actually will rename any files that don't conform." - but i guess there is no check for the correct values itself? in my case the manufacturer was wrong in the media files.

**Comment by mjrgh** [comment]
Re the <game name="xxx"> element: you're right, that's just the name of the .vpx file, as it should be.  This whole XML schema is based on the PinballX/HyperPin schema (to allow reusing existing databases), not something I made up, and clearly I'm still getting confused about it.  

And re the system name mismatch: I'm glad you figured it out.  But regardless of the system name mismatch, it actually should still have gotten the destination filenames right when you imported the media pack.  The installed media files should have their names changed to match the actual game's media name, regardless of the names found in the media pack.  So even if the system was "wrong" in your database when you installed the media pack, it shouldn't have mattered:  the same wrong name should have been copied over to the installed filenames, and the files should have been found and displayed.  So something's screwy there.  I'll see if I can reproduce it and track down what went wrong.

**Comment by mjrgh** [comment]
One question, if you're still monitoring this.  You said:

2. Downloaded the media pack from here: https://www.vpforums.org/index.php?showtopic=10436
3. Drag and dropped all the files into pinbally.

When you dropped the files, did you drop them individually, or did you just drop the ZIP file itself?  "Dropped all the files" makes me think you opened the ZIP and dropped the files separately - I want to make sure I'm looking at the right test case.  If that's what you did, by the way, the easier way is to just drop the ZIP file itself, as the program can use the ZIP folder layout to determine where each file goes.
