### ISSUE TITLE
Returning to PinballY, backglass in no longer Full Screen

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#43]
I have been trying to find some sort of "pattern" to this but haven't, reporting anyway.

What happens is as described - I exit VPX (pinup is not an issue here, doesn't matter) and sometimes, the backless, while the software *thinks* it is "full screen" is actually windowed and the original size, as if the setting has been erased. Selecting "Full Screen" doesn't go to full screen in this instance; it turns off the borders. Doing it again goes to full screen.

Once this starts happening, it is constant until reboot.

**Comment by mjrgh** [comment]
Let me know if you can find some kind of pattern to it - if I can reproduce it, I can investigate.

One troubleshooting suggestions: Next time it happens, take a look at the Settings.txt file (while the program is still running) and see what the backglass window settings look like.

**Comment by kaicherry** [comment]
Noted. Thanks for the tip on a place to look, because I don't like reporting things where I can't find the "Steps to rent" besides 'wait for it" :)

**Comment by githubmarie** [comment]
Hi have the same issue (W764, PBY32). When I exit my first VPX table and return to PBY, my backglass is small/ not full screen.
It happens only for the fir
st table that I open though. 
When I then set the backscreen to fullscreen again (by right mouse click). The backglass appears full screen for all tables. 
After restarting PBY, same issue again. 

Note: this only happens when NOT using forced full screen. 
With forced fullscreen ON there are NO problems with the backglass and everythings runs fine.

The settings.txt did not show any changes btw

**Comment by mjrgh** [comment]
I'm still not exactly sure what's going on, but I'm guessing that it's due to a display configuration change caused by VP or B2S - maybe a monitor resolution change or DPI settings change.  In any case, the beta 7 now saves and explicitly restores the window placements across a game launch.  Hopefully that'll put everything back where it's supposed to be after each game session.  Give it a try and let me know if it solves the issue for you.

**Comment by githubmarie** [comment]
I just tested beta 7 and it works perfectly for both Forced Full screen ON and OFF.

**Comment by kaicherry** [comment]
Looks good, I haven't seen this happen with this build.

**Comment by mjrgh** [comment]
Great - thanks to both of you for testing it out!
