### ISSUE TITLE
Capturing depends on dimensions of PinballY window

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#48]
Steps to reproduce on latest beta:

1. Start PinballY. If in Fullscreen, exit to window.
2. Navigate to Edit Game/Capture media
3. Choose Playfied Image/Playfield Silent/Skip everything else
4. Start Process

Process completes with cropped playfield recording.

**Comment by mjrgh** [comment]
Right, that's by design.  What behavior did you want instead?

**Comment by kaicherry** [comment]
Ok. So, as a user, I would have expected it to capture the whole play field. If this is not supposed to work this way, maybe an alert like "Capturing in windowed mode doesn't capture the full screen. Continue?" with a "Don't show me this again" option?

Now that I know, I will make sure it is fullscreen... :)

**Comment by mjrgh** [comment]
> So, as a user, I would have expected it to capture the whole play field.

The thing is that "the whole play field" isn't a concept that the program understands, since the game is a separate program with its own windows.  The game might combine the playfield and backglass in a single window, for example.  So to keep things simple, PinballY captures the area defined by **its own** windows, which lets you arrange things as needed before starting the capture.  I could add a message about that the first time you run a capture, I suppose.

**Comment by kaicherry** [comment]
Up to you. Had I expected it (and yes, it makes sense, the 'UX' doesn't make this clear, use cases, etc) it wouldn't have been perceived as a bug. I/you can close this one out?

**Comment by mjrgh** [comment]
FYI - I added a message at the start of the capture process in beta 8 explaining how the screen area for capture is chosen.
