### ISSUE TITLE
DOF trigger for launch table

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#54]
Hi MJR,

PinballY have a DOF trigger when exiting a table, could you add  one when a table is launch (when playing the launch audio).

**Comment by mjrgh** [comment]
I'll add it to my list.  

Note that any DOF effects you base on this trigger might get cut off before the launch audio finishes playing, because PinballY has to disconnect from DOF before the game starts to allow the game to take over the DOF devices.  DOF doesn't have any ability to share access between two processes, so it's critical for PinballY to terminate its DOF connection early in the launch process to ensure that the game doesn't encounter errors trying to start its own DOF connection.  When PinballY disconnects from DOF, any device effects triggered based on PinballY events/states will immediately stop, because DOF turns off all devices at disconnect.

**Comment by mjrgh** [comment]
Added in Beta 10.
