### ISSUE TITLE
Use of both flippers for playfield capture

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#59]
Pressing both flippers to start a playfield capture is not good because a flipper movement is captured in the video as the flippers are released. This occurs when the user decides to start a game before capturing a video. Either add a small delay or use a different action like "launch ball".

**Comment by mjrgh** [comment]
Well, a delay obviously wouldn't be desirable because the whole point is to let the user control the timing.  I see your point about wanting to capture a video of an active game, but I chose the flipper buttons precisely because they wouldn't have an effect when capturing video of attract mode.  I'll look at maybe adding an option to set different buttons for this.

**Comment by mjrgh** [comment]
The beta 12 has a new option that lets you select a different button or buttons for the manual start/stop command.  Hopefully that'll solve this for you.
