### ISSUE TITLE
Pinball Arcade Cabinet Support

### ISSUE THREAD

**Issue by sebinouse** [mjrgh/PinballY#7]
I've this error message when I try to launch the cabinet dedicated exe of Pinball Arcade.
![img_1480](https://user-images.githubusercontent.com/9035443/45597363-70fe1700-b9cb-11e8-9c76-26d02da9fa68.jpg)
If I click "Ignore" several times (about x6) the application runs in background behind PinballY, and PinballY does not see the program running.

No issue if I run directly PinballArcadeCabinet.exe from windows explorer with PinballY running in background.

Do we need a specific Visual C++ runtimes version ?
(I've got a Kinect v2 which is not connected for the time being, tell me if it's related)

**Comment by mjrgh** [comment]
Hi - that error is coming from Pinball Arcade, and I believe it's because you're trying to launch its EXE directly rather than through Steam.  You have to launch it through Steam.exe.

**Comment by mjrgh** [comment]
You might try looking at the Steam forums - if you do a web search for "pinballarcade11.exe", there are a bunch of posts from other people struggling with getting the DX11 version to launch directly.  There might be some tricks they've figured out that would also apply to the cabinet version, since that DX assertion error you ran into also happens with the pinballarcade11.exe version when launched directly.

**Comment by sebinouse** [comment]
I managed to get rid of this error by using a script yo hide PinballY before launching PinballArcade cabinet.

An other user, [GAH1068](url
http://www.digitalpinballfans.com/showthread.php/13478-Running-noex-FCM-for-non-arcooda-tables-s7?p=278404&viewfull=1#post278404), reported the same issue and was killing PinballY before launch.

`System7 = Pinball Arcade Arcooda
System7.Enabled = 1
System7.MediaDir = 
System7.DatabaseDir = 
System7.Class = 
System7.Exe = C:\Scripts\Run_Arcooda.exe
System7.Parameters = 
System7.Process = PinballArcadeCabinet.exe
System7.StartupKeys = 
System7.TablePath = 
System7.NVRAMPath = 
System7.DefExt = 
System7.DOFTitlePrefix = FX3
System7.RunBeforePre = 
System7.RunBefore = 
System7.RunAfter = 
System7.RunAfterPost = `


Run_Arcooda AHK script compiled to exe
`;ROTATE SCREEN
Run, "C:\Scripts\display.exe" /device 1 /rotate 90 /display none,, Hide

;LAUNCH
WinHide, PinballY
SetWorkingDir, C:\Program Files (x86)\Steam\steamapps\common\PinballArcade
Process, Close, PinballArcadeCabinet.exe
Run "C:\Program Files (x86)\Steam\steamapps\common\PinballArcade\PinballArcadeCabinet.exe"
WinShow, PinballArcadeCabinet

;PRESS ESC TO QUIT
~Escape::

Process, Close, PinballArcadeCabinet.exe
Run, "C:\Scripts\display.exe" /device 1 /rotate 0 /display none,, Hide
WinShow, PinballY

Sleep 1000
ExitAPP
return`

**Comment by mjrgh** [comment]
Try out the new Alpha 21 when you get a chance.  It should eliminate the need to hide any windows.  Just follow the new recipe in the System Options help file for Pinball Arcade DX11, substituting the cabinet exe.

The source of the assert failures turned out to be that PinballY was launching Pinball Arcade with the initial window open mode set to "minimized".  The Pinball Arcade program was evidently trying to use the 0x0 pixel size of the minimized window to set up its DX11 buffers, which caused all kinds of internal errors.  I added a new Window Mode option to the system settings, which you can set to "Show" for Pinball Arcade launches.  The DX11 version also needs a couple of environment variables to be set, or it won't launch properly, but I guess that must not be required for the cabinet version given that you got it to launch on its own without them.

**Comment by sebinouse** [comment]
I've been testing for several minutes ... and it's working great ! Thanks A LOT !

**Comment by mjrgh** [comment]
Great!  Thanks for testing it out.  I'll close this issue out for now - feel free to reopen it if you run into any new problems with it.
