### ISSUE TITLE
Batchwindow in PinballY

### ISSUE THREAD

**Issue by Harry295** [mjrgh/PinballY#72]
**If this is your first bug report**
Please read [How to write a good bug report](https://github.com/mjrgh/PinballY/wiki/How-to-write-a-good-bug-report)

**Describe the bug**

**To Reproduce**
Exact steps to reproduce the behavior.  Please be as complete and detailed as possible: **pretend** that we can't read your mind or see what you're doing with the mouse.

**Expected behavior**

**Test files**
If applicable, add any test files (images, videos, configuration files) needed to illustrate or reproduce the problem.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Harry295** [comment]
I have a problem with PinballY:
When I create a new playfieldimage the batchwindow always will be recorded too..

**Comment by Harry295** [comment]
https://www.flippermarkt.de/community/forum/threads/pinbally-problem.207828/#post-1642650

**Comment by mjrgh** [comment]
By "batchwindow", I assume you're talking about the capture status window?

If PinballY isn't moving that out of the way when recording starts, it's probably because PinballY doesn't know where the playfield window is supposed to be.  Have you read the section in the Help about Capture?  In particular, pay attention to **How does PinballY determine the screen area to capture?**

**Comment by Harry295** [comment]
Hello mjrgh,many thanks for your message.PinballY is a great programm !!I fixed the problem instead. The pinball ChampionsLeague18 started with a error message because of a problem with windows defender. To solve this error message the only reason was to run visualpinnball.exe in admin mode. PinballY tolerate this not and so i can't get the pictures fom the table..The reason was to deactivate the user account control in windows10.When i now record the pictures from the tables all is OK !Suggestion :I get my videos fom PinUpPopper. There were tables pinballX and pinball9.When i copied the videos to pinballY i had to rotate the videos 180 degrees.Unfortunately you seperate the imagefolders pinballx and pinball9.So when the videos run in the game wheel and the program has to change between pinballx and pinball9 there were some blurring or the video runs not correct.In my opinion when the images were in one folder it would run better.To fix this problem i let run only videos from pinballx and show pictures from pinball9.Or could i ajust this myself ?I look forward to your answerGeorg mjrgh <notifications@github.com> hat am 11. Mai 2019 um 01:32 geschrieben:  By "batchwindow", I assume you're talking about the capture status window?If PinballY isn't moving that out of the way when recording starts, it's probably because PinballY doesn't know where the playfield window is supposed to be. Have you read the section in the Help about Capture? In particular, pay attention to How does PinballY determine the screen area to capture?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mjrgh** [comment]
A couple of notes:

1.  You really shouldn't turn off UAC or run anything pinball-related in Admin mode.  For security reasons, Windows imposes a lot of restrictions on interactions between elevated (Admin-mode) and non-elevated (regular user mode) programs, which is why things like keyboard monitoring and screen capture don't work properly when anything is in Admin mode.  Windows is trying to prevent malicious software from capturing sensitive information from elevated programs, so it locks down a lot of aspects of your system when an Admin mode program is running.

In most cases when people **think** they have to run something pinball-related in Admin mode, there's actually a better solution that doesn't involve Admin mode.  But if you are absolutely certain that you've ruled out every other alternative, you should (a) **not** turn off UAC, and (b) run the "PinballY Admin Mode.exe" program.  **Do not** run PinballY.exe with right-click "Run as Administrator".

2.  You can change any of the media folders by going to Settings > Visual Pinball 9 (or whichever system) and entering a custom folder in the Media Folder box.  See http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html.
