### ISSUE TITLE
Autostart PinballY after starting Windows 10 doesn't focus on main screen

### ISSUE THREAD

**Issue by Calimerorulez** [mjrgh/PinballY#76]
Hi,

First of all thank you for creating this awesome program :-)

I just installed PinballY on my freshly installed Windows 10 (fully updated). When auto starting PinballY after booting Windows, the main screen of PinballY does not get the focus, so I need to Alt-Tab to enable the PinballY main screen.

Is there a solution for this?

Thanks and greetings from The Netherlands.

**Comment by mjrgh** [comment]
This seems to be an intentional feature of the Windows 10 Task Scheduler.  Microsoft apparently intentionally changed it in Win 10 so that scheduled programs don't get focus.  The rationale seems to be that most scheduled programs are meant to be background tasks, so you don't want them suddenly popping up and stealing focus from whatever the user is doing.  Unfortunately, they made the change mandatory; it would have been nicer if they'd offered a checkbox to say whether or not to set focus on the new program.

The workaround Microsoft suggests on their support site is to use cmd.exe to launch the program.  Give this a try and see if it helps:

- Open Task Scheduler

- Find the PinballY startup task

- Edit it

- Go to the Actions tab

- Double click the "start a program" action

- Copy the PinballY program path from the "Program/Script" box to the "Add arguments" box

- Change Program/Script to **cmd.exe**

- Change the arguments to:   /c "" "c:\path\pinbally.exe"

"OK" out of all of the nested dialogs.

Hopefully that'll do the trick.  Let me know if it works.  If so, I'll see if I can find a way to do this with fewer manual steps in a future update.

**Comment by Calimerorulez** [comment]
Hi,

I changed the scheduled task like you said, now the backglass is getting the focus everytime after startup. I will try the startup short cut later.

Thanks again.

**Comment by mjrgh** [comment]
Okay, let me know if the shortcut works better.

Just out of curiosity, when you say "the backglass is getting the focus", what do you mean exactly?  It really shouldn't matter which PinballY window has focus as long as one of them has focus, since they all route key input to the main window.  What kind of problems/symptoms do you see when the backglass has focus?

**Comment by Calimerorulez** [comment]
I haven't had the time to test the startup shortcut yet (sorry), but when I autostart PinballY, I have to use my mouse to click the playfield window, because if I don't, the button inputs, e.g. from my left and right flippers aren't being passed through to PinballY. I can't browse tables then, that's why :)

**Comment by mjrgh** [comment]
> but when I autostart PinballY, I have to use my mouse to click the playfield window, because if I don't, the button inputs, e.g. from my left and right flippers aren't being passed through to PinballY. 

Earlier, though:

> now the backglass is getting the focus everytime after startup.

I thought you meant the PinballY backglass window, but maybe you meant something else?  That's what I was asking about.  If the **PinballY backglass window** has focus, it should be the same as PinballY having focus.  If you're observing some situation where the PinballY backglass window has focus but PinballY isn't receiving keystrokes, that would be surprising, which is why I asked.  Perhaps that's not what you meant, though?

**Comment by Calimerorulez** [comment]
I will experiment further, now it is confusing me too...

**Comment by mjrgh** [comment]
Okay, let me know if you find anything new.  

One other thing I should have suggested that you can try is to add a delay to the launch.  It's possible that the problem is that some other program is getting auto-launched shortly after PinballY is auto-launched, and the other program steals focus when it comes up.  Typically the last program to take focus keeps focus, so the order of launching things can make all the difference.  The PinballY settings for auto-launch have a delay setting for just this purpose, and you can also set the timing in Task Scheduler.  If you switch to the Start menu Startup group approach, I don't think there's any formal way to set timing there, although you might be able to jury-rig something with a CMD batch script.
