### ISSUE TITLE
Can't Find Visual Pinball X executable and thus cannot launch any VPX table.

### ISSUE THREAD

**Issue by danfleck** [mjrgh/PinballY#77]
After installing PinballY (coming from a PinballX setup). I see all my tables, but the launcher for them is always set to "Visual Pinball 9". 

Each table is a .vpx file.

When I go to the operator menu to change the game details the dropdown for available programs shows only VP9 and VP9.2... it doesn't show VP X. 

From the options menu, VPX is enabled. I tried also setting the actual path to the executable and it said it was already the default location for the "Visual Pinball X.exe" so I shouldn't set it. I tried setting it anyway and it didn't make any difference.

Ideas?

**Comment by mjrgh** [comment]
Try this:

* Open the help
* Go to the Troubleshooting section
* Follow the steps under "PinballY isn't finding my tables"

(I know that doesn't sound like exactly the right topic to diagnose this particular problem, but it probably is: the problem is probably that you have things set up in such a way that PinballY is mistaking your Visual Pinball 10 installation for a Visual Pinball 9 installation.  The troubleshooting steps there will help you understand why that is, which should point you to what you need to change to fix it.)

**Comment by danfleck** [comment]
Thanks for the response. I think the problem seems to be its setting tables
as both VP9 and VPX. Regardless it does seem to find VPX but doesn't show
it in the dropdown of possible choices when setting the game options
manually.

I know when I first added tables to PinballX I did it probably not the
right way (I didn't import media packs and generally had no idea what I was
doing).

Logfile attached.

Let me know what else I should try.

Thanks!

**Comment by mjrgh** [comment]
Did you try reading through the log? It's meant to be helpful so you can figure it out.

**Comment by danfleck** [comment]
Yes, I read the log. It looks like I would expect it. It says that the tables for VPX are found and the emulator path is correct. The only thing that seems odd is that VP9 section lists all my tables (and none of my tables are VP9 except Escape). 

> + System "Visual Pinball 9": loading table database file C:\PinballX\Databases\Visual Pinball\Visual Pinball.xml
++ This is the main file for this system (it doesn't define a category)
++ adding game ACDC, table file AC-DC_Premium-1.4, media file base name ACDC (Stern 2013)
++ adding game Attack From Mars, table file AFM_1.3.0, media file base name Attack From Mars (Bally 1995)
++ adding game Big Game, table file Big Game (Stern 1980), media file base name Big Game (Stern 1980)

**Comment by danfleck** [comment]
Not sure if the log attachment worked on the earlier post. Here is the log again.
[PinballY.log](https://github.com/mjrgh/PinballY/files/3494551/PinballY.log)

**Comment by danfleck** [comment]
I got it to work by disabling the other Visual Pinball versions and then I changed the media directories. I believe it was the media directories possibly being duplicated that caused the problem of not showing the VPX emulator at all. Overall I really like PinballY..thanks!

**Comment by mjrgh** [comment]
Glad you got it working!

If you have the time, I'd be interested in getting some details on your thought process as you were attempting to solve this, to see if there's something I can add to the log that would have made the solution clearer for you.  What would be most helpful, I think, is if you could go over the log step by step and tell me what's going through your mind at each step, particularly asking yourself how each item in the log file bears on the central question here, "Why does PinballY think this game is a Visual Pinball 9 game when *I* know it's for Visual Pinball X?"  Maybe I can figure out some little snippet of information I could add or change that would have clarified this for you with less effort, so that the next person who runs into the same sort of problem will be able to go straight to the solution.

**Comment by mjrgh** [comment]
Here, I also added a new Troubleshooting topic for this specific case:

http://mjrnet.org/pinscape/downloads/PinballY/Help/Troubleshooting.html

Scroll down to "PinballY thinks my Visual Pinball X tables are Visual Pinball 9 tables".

If you want to read through that, let me know if that would have solved the problem for you earlier, and if there's anything you'd add or revise.

**Comment by danfleck** [comment]
Thanks... the new troubleshooting would have helped a lot. I would also add something about PinballX not showing up as a choice in the Game Setup -> Games Details -> System dropdown. The first debugging I tried was to set that dropdown to PinballX but PinballX did not show up as an option in the dropdown. Is that somehow caused by the database/path problem? 

The other question I still have is that i'm not quite sure why the database problem was a problem. I assumed since the extension was .vpx there should be no way it would think it was a VP9 (.vpt) table. This is probably my lack of depth in Visual Pinball but it was very odd because that would seem like the only thing required to know it was a VPX table versus VP9.

One last note you may want to know is that when I did change it I still lost some media, but not all media (e.g. some of my wheel images, table images don't show in PinballY). So I can go and reconfigure them but it wasn't quite a seamless switch from PinballX. 

I'm also dealing with the PinMame DMD (virtual on a 3rd screen) doesn't stick where the PinballY DMD is. I think that's a different problem I'll mention in the forums if I can solve it though.

**Comment by mjrgh** [comment]
> I would also add something about PinballX not showing up as a choice in the Game Setup -> Games Details -> System dropdown. 

Is there something you'd change in the phrasing of "PinballY thinks my Visual Pinball X tables are Visual Pinball 9 tables"?  Because that was meant to answer that exact question.   Whatever you can tell me about what was going through your mind at the time would be helpful - what topic would you have looked for in a troubleshooting list at that point?

> The other question I still have is that i'm not quite sure why the database problem was a problem.

You might try reviewing this help section: 
 http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html - particularly the section on Database Files.

**Comment by danfleck** [comment]
To me when the game tried to load in VP9 my first thought was somehow PinballY thought it was a VP9 table. So I need to tell it explicitly to use VPX. So I checked the settings and saw the extension for VPX was correctly (.vpx) and VP9 was correctly (.vpt). Then I thought okay, maybe somehow each game got a specific setting I needed to manually fix. So I went to the game setup and looked at the system and wanted to select “VP 10” or “VP X” but the only options in my dropdown were VP 9 and VP9.2. So my thought was not that it was a table-mislabeling problem but that it was a problem that PinballY didn’t understand I had VPX installed and therefore it wasn’t an option in that dropdown. 

My thought was I need to make PinballY think that VPX is installed and once I do that, the option in the game setting—>System menu will let me choose “VP10”.

So I wouldn’t change your phrasing but I would add another troubleshooting somewhat like: “Visual Pinball X is not available in the Systems dropdown”. I was definitely on the wrong track thinking it was an installation problem with VP10. It does feel like a bug that the dropdown option disappeared when the directories were setup in a conflicting or odd way. 

Aha! I found it… I just tried to go ahead and re-enable VP9 to see if the problem came up and it did, but this time an error message showed up that I never saw before. The error is very clear “In your “settings.txt” file the system Visual Pinball 9 and Visual Pinball X are configured with the same table database folder. Each system needs a separate folder. Visual Pinball X will be disabled for this session”.

That’s the error message I needed to see. Maybe it doesn’t come up on a fresh install when a user has this problem? That would have quickly gotten me to the answer. I only see it now that I have disabled VP9 and then re-enabled VP9.

**Comment by mjrgh** [comment]
> So I wouldn’t change your phrasing but I would add another troubleshooting somewhat like: “Visual Pinball X is not available in the Systems dropdown”.

Okay, I'll try working in a topic to that effect.

> That’s the error message I needed to see. Maybe it doesn’t come up on a fresh install when a user has this problem? 

Well, that error doesn't come up in a fresh install, because there isn't such an error in a fresh install!  As I tried to explain in the new troubleshooting topic, the initial default settings for the database folders are:

* (system) Visual Pinball 9  -> (database folder) "Visual Pinball"
* (system) Visual Pinball X -> (database folder) "Visual Pinball X"

When you changed the Visual Pinball X system database folder to "Visual Pinball", that's when the conflict was created.  It didn't exist until then, so there was no error message before then.  But you didn't see it at quite that moment, because you *also* disabled the entire Visual Pinball 9 system at the same time - so the conflict *still* didn't exist yet because Visual Pinball 9 was not a factor at that point.  The message finally did appear when you re-enabled Visual Pinball 9 with the conflicting folder setting, because at that point you had two active systems using the same database folder.  Make sense?

**Comment by danfleck** [comment]
Thanks… yes that makes sense. So the error isn’t there, but possibly since the database directory "Visual Pinball X" is missing the entry in the dropdown is gone? Is that why the dropdown didn’t have VPX ? That’s the main confusing thing I was trying to figure out when this happened.

**Comment by mjrgh** [comment]
> So the error isn’t there, but possibly since the database directory "Visual Pinball X" is missing the entry in the dropdown is gone? Is that why the dropdown didn’t have VPX ? 

No, I'm afraid that's not quite it.  Maybe try reviewing the help section on table databases again, with this question in mind:

"How does PinballY find tables to display in the list of available tables?"

The answer to that question should tell you the answer to the next question:

"Why does PinballY think that game X is for system Y?"

And the answer to that question should tell you:

"Which systems are listed in the drop-list for game X?"

**Comment by danfleck** [comment]
Okay, let me see if I have this right then. 

I’m assuming that the idea of a game that is configured or un-configured means it is in a table databases file somewhere or it’s not. Is that right?

So to get a new (unconfigured) game into a table database you go through the setup process and I assume can choose any system you have installed and the setup process will add the game to that system’s table database?

But once a game is configured there isn’t really any way through setup to add it to a new table database? 

In my case it happened to be in two table databases (VP9 and VP9.2) and that’s why for a configured game I had more than one system option available in the dropdown. But that wouldn’t be possible to do through PinballY it’s just an artifact of moving from PinballX.

If this is right (and that’s a long shot :-) then maybe adding an ability to move/copy the game from one table database to another from setup makes sense. 

Or does “unconfiguring” a game already remove it from a table database? That could be a workaround to unconfigure it and then (if configuring a game lets you choose any system you have installed) reconfiguring under the new system would work. 

One main confusion I had was that I assumed that the system dropdown controlled the table databases file, but really the table databases file controls what is in the dropdown.

**Comment by mjrgh** [comment]
> I’m assuming that the idea of a game that is configured or un-configured means it is in a table databases file somewhere or it’s not. Is that right?

Right, exactly.

> So to get a new (unconfigured) game into a table database you go through the setup process and I assume can choose any system you have installed and the setup process will add the game to that system’s table database?

No, not exactly.  

Consider where *unconfigured* games come from: does PinballY just scan every file on your entire hard disk and think that's a game? Probably not, right?  

So, which games *are* considered game files?  The ones that match the table path and extension for some system.

So, is there a system automatically associated with an *unconfigured* game file?  Yes: the system or systems that provided the table path and extension that the file matched.  There might be more than one, because systems sometimes share the same path and extension.  For example, Visual Pinball 9,  Visual Pinball 9.2, Visual Pinball Phys Mod 5, and Visual Pinball X all share the same table path, and the first three of those all use .vpt extensions.

Does it make sense now why Visual Pinball 9 and Visual Pinball 9.2 might show up as the options for a game file?

**Comment by danfleck** [comment]
Yes that makes sense. Between now and then I've added games through
PinballY and it's very clean and simple.

Every once in a while the focus doesn't go back to PinballY after game
exit. I think from tables with UltraDmd. I'm looking for a solution. I'll
post a question into a different thread if I can't solve it after I look
around for troubleshooting tips to solve it.

Thanks for your help!
