### ISSUE TITLE
Random crashes in ntdll.dll!RtlpWaitOnCriticalSection()

### ISSUE THREAD

**Issue by byancey** [mjrgh/PinballY#88]
**Describe the bug**
PinballY crashes randomly in ntdll.dll RtlpWaitOnCriticalSection, This sometimes occurs while interacting, sometimes while attract mode is running.  Odds are pretty good it will occur if I just fire up the front-end and let it run for a few hours, but I have seen it go as long as 7 hours.  Also, I have only reproduced this on my cabinet.  I have not seen this on my laptop running the same configuration (though windowed views rather than fullscreen on multiple displays).

I'm not entirely convinced this is a PinballY issue as opposed to something specific to hardware or software on my cabinet, system libraries, etc, but I'm posting this as a new issue for a discussion started in issue #86 

I've managed to capture the failure in the debugger close to a dozen times or so, and the signature is always pretty much the same.  The exception is always "0xC0000005:` Access violation writing location 0x0000000000000024" with the same basic entries on the call stack,   There are no entries on the call stack from within PinballY source code, and I do not have any symbol information available for any of the entries on the stack, so the only clues are really the call stack itself, which looks pretty consistent with each crash.

I've included a screenshot with the stack trace and exception info in the screenshot section of this report.

A couple of other considerations.  I have made a number of customization on my branch, so this is not "stock" PinballY, and this could be something I introduced.  Looking through my commits, there aren't many I believe could cause this.   A couple stand out:

1. I migrated from XAudio 2.7 to XAudio 2.9 and removed the dependency on the legacy June 2010 DirectX SDK, since I don't require support for Windows 7.
2. I changed the time for the media transitions from 200ms to 0ms.

Oh, I also updated libvlc to the latest version 3.0.8 on Mike's suggestion just to see if that helped...it didn't.

I am planning to revert back to the released version of PinballY this evening and see if the problem goes away, which should either eliminate or implicate one of my changes as the issue.

**To Reproduce**
In my case, just fire up my cabinet and let it run a few hours.  Have not been able to reproduce on a second system.

**Expected behavior**
Run forever without crashing. :)

**Test files**
I have a crash dump available.

**Screenshots**
Here's a screenshot of the exception info and call stack.  If anything on here suggests a possible solution, please let me know:

![image](https://user-images.githubusercontent.com/7484658/66368584-00b79000-e956-11e9-8f48-2fa6eaa67bbf.png)

**Windows version**
Windows 10

**Comment by mjrgh** [comment]
You know, looking at that stack trace, it looks like you're crashing down in your video card drivers.   I take all of those entrypoints below d3d9.dll to be Nvidia device drivers - nvspcap64.dll, nvd3dumx.dll, nvldumdx.dll.  So I wonder if you might be hitting a video driver bug.  It might explain why you're only seeing it one machine.

It might be worth checking to see if you're on the latest video drivers for your card.  Same thing applies here as the libvlc update, though - not a magic bullet, since there's no reason to think Nvidia would have fixed the bug even if it actually is theirs, or that they even know about it.  Still, easy to try to rule it out.

I think your intuition about changing the 200ms staggering could be worth exploring, too.  If it is in fact a problem somewhere down the stack (libvlc, D3D9, Nvidia), you might be greatly increasing the odds of triggering it by launching multiple video streams at the same instant.  Putting back a slight stagger might reduce the odds of the crash enough to effectively get rid of it.  Not what I'd consider a "fix" if it actually is a PinballY bug, but if it is in fact a third-party bug, that might be the best chance for a workaround.  If this is in fact the decisive factor, then I'd guess that you could probably find a happy compromise stagger time that's short enough to be mostly imperceptible but long enough to avoid the driver crash - maybe 10ms or 20ms.  Anyway, another thing that might be worth a shot.

________________________________

**Comment by byancey** [comment]
Updated my video drivers a few weeks back, and they are still on the latest.

I just finished rebuilding debug against master, and I've fired it up for another test run.  If it still crashes in this state with the same signature, I'll shift focus to the video card.   I have an RTX2080 TI sitting in a graphics amplifier for my laptop that I can easily pull and play around with in my cabinet.  It would be overkill to leave it in there...but useful for isolating the problem. :)

If it runs overnight without crashing, I'll go back to my feature branch and revert just the 200ms fade timers and see how things go.

I appreciate all your input on this Mike...especially considering this one might not be a PinballY issue at all.

Thanks!

**Comment by byancey** [comment]
So, same crash running without any of my changes.

Pulling on the graphics card thread a bit more, specifically the driver where the crash occurs is nvscap64.dll.  The only reason I have GEForce installed is for convenience in keeping my graphics drivers up-to-date.  I do not use the ShadowPlay feature and did not enable it, but it seems it is perhaps running in shadow mode and keeping a running capture of the last 20 minutes of game play.

I have uninstalled GEForce and kicked off another test run.

**Comment by byancey** [comment]
Running 8 hours straight with no issues.  At the risk of declaring victory too soon , I'm going to go ahead and declare victory (again). :)

For the last few days while I've been running with the debugger I've seen crashes anywhere from within a few minutes to within an hour or so.  This debugger run has now been up for over 8 hours straight with no failures.  Based on the presence of Nvidia ShadowPlay drivers in every single crash, it seems clear that eliminating that from the equation has also eliminated whatever critical resource contention with was causing the crash.

Thanks again Mike for the help on isolating this.  I'm going to go ahead and close this issue.
