### ISSUE TITLE
High Scores from Pinball FX3

### ISSUE THREAD

**Issue by cherlihy71** [mjrgh/PinballY#97]
I was wondering if there was a way to display tables with their local high scores from Pinball FX3?

As a tag I can add to the status line option or something similar?

Thanks!

**Comment by mjrgh** [comment]
I don't think there's any high score integration with FX3.  High scores are handled through PinEMHi, and as far as I know it only supports VP and FP.  

If you know how to get the high scores out of FX3, it should be pretty easy to use Javascript to grab those and display them in the status line.  In the help files, see the Javascript scripting > Events > Event Types > HighScoresEvent.  That section explains you how to customize the high score lookup for systems that PinEMHi doesn't handle.  If you know how to get an FX3 score out of a file on the disk or something like that, you could use the event to do that file lookup.  

That'll make high scores show up in the usual places (DMD window and game info popup).  As for display on the status line, high scores aren't in the standard set of variables, and you probably wouldn't want them there since not every game has high scores (I think it would probably look too clunky to display some placeholder text like "high scores unknown" when they're not available).  But what you could do is use the status line update events in Javascript to insert them when available.  See Javascript scripting > Events > Event Types > StatusLineEvent

If you can put something like this together for FX3, it would make a great addition to the Javascript Worked Examples section in the help.

**Comment by cherlihy71** [comment]
Thanks!  I do some digging and see what I can turn up!

**Comment by xantari** [comment]
@cherlihy71 Did you find any info on this? From what I can see the highscore data in pinball FX2/FX3 is in some wierd binary format in the steam folder, looks to be encrypted. I've been trying to find how to read them but can't figure it out.

**Comment by mjrgh** [comment]
If anyone ever figures this out, I'd be happy to add integration to PinballY, but it sounds like it's not feasible (maybe deliberately so, if they're encrypting the data).
